## CONFIG

In [ ]:
!pip install pyAudioAnalysis
!pip install kagglehub
!pip install soundfile
!pip install tqdm
!pip install scipy
!pip install matplotlib

## Código

In [ ]:
import kagglehub

path = kagglehub.dataset_download("ulianazb/asvspoof-2024") #baixa dataset inteiro, muito grande

print("Path to dataset files:", path)

In [9]:
import kagglehub
from pathlib import Path
# soluçao para baixaar apenas os 100 primeiros
arquivos = []

for indice in range(100):
    nome = f"T_{indice:010d}.flac"
    caminho = kagglehub.dataset_download(
        "ulianazb/asvspoof-2024",
        path=f"flac_T/flac_T/{nome}"
    )
    arquivo = Path(caminho)
    if not arquivo.is_file():
        raise FileNotFoundError(f"Arquivo nao encontrado: {arquivo}")
    arquivos.append(arquivo)
    print(f"{indice + 1}/100: {arquivo}")

print(f"Arquivos disponiveis: {len(arquivos)}")
print("Pasta local:", arquivos[0].parent)

Downloading to C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T/flac_T/T_0000000000.flac...

100%|██████████| 167k/167k [00:00<00:00, 256kB/s]

1/100: C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T\flac_T\T_0000000000.flac
Downloading to C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T/flac_T/T_0000000001.flac...

100%|██████████| 120k/120k [00:00<00:00, 246kB/s]

2/100: C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T\flac_T\T_0000000001.flac
Downloading to C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T/flac_T/T_0000000002.flac...

100%|██████████| 175k/175k [00:00<00:00, 235kB/s]

3/100: C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T\flac_T\T_0000000002.flac
Downloading to C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T/flac_T/T_0000000003.flac...

100%|██████████| 198k/198k [00:00<00:00, 300kB/s]

4/100: C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T\flac_T\T_0000000003.flac
Downloading to C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T/flac_T/T_0000000004.flac...

100%|██████████| 296k/296k [00:00<00:00, 440kB/s]

5/100: C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T\flac_T\T_0000000004.flac
Downloading to C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T/flac_T/T_0000000005.flac...

100%|██████████| 216k/216k [00:00<00:00, 297kB/s]

6/100: C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T\flac_T\T_0000000005.flac
Downloading to C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T/flac_T/T_0000000006.flac...

100%|██████████| 215k/215k [00:00<00:00, 348kB/s]

7/100: C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T\flac_T\T_0000000006.flac
Downloading to C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T/flac_T/T_0000000007.flac...

100%|██████████| 245k/245k [00:00<00:00, 425kB/s]

8/100: C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T\flac_T\T_0000000007.flac
Downloading to C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T/flac_T/T_0000000008.flac...

100%|██████████| 178k/178k [00:00<00:00, 288kB/s]

9/100: C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T\flac_T\T_0000000008.flac
Downloading to C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T/flac_T/T_0000000009.flac...

100%|██████████| 206k/206k [00:00<00:00, 371kB/s]

10/100: C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T\flac_T\T_0000000009.flac
Downloading to C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T/flac_T/T_0000000010.flac...

100%|██████████| 187k/187k [00:00<00:00, 346kB/s]

11/100: C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T\flac_T\T_0000000010.flac
Downloading to C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T/flac_T/T_0000000011.flac...

100%|██████████| 294k/294k [00:00<00:00, 352kB/s]

12/100: C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T\flac_T\T_0000000011.flac
Downloading to C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T/flac_T/T_0000000012.flac...

100%|██████████| 140k/140k [00:00<00:00, 201kB/s]

13/100: C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T\flac_T\T_0000000012.flac
Downloading to C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T/flac_T/T_0000000013.flac...

100%|██████████| 159k/159k [00:00<00:00, 297kB/s]

14/100: C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T\flac_T\T_0000000013.flac
Downloading to C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T/flac_T/T_0000000014.flac...

100%|██████████| 198k/198k [00:00<00:00, 325kB/s]

15/100: C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T\flac_T\T_0000000014.flac
Downloading to C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T/flac_T/T_0000000015.flac...

100%|██████████| 138k/138k [00:00<00:00, 226kB/s]

16/100: C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T\flac_T\T_0000000015.flac
Downloading to C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T/flac_T/T_0000000016.flac...

100%|██████████| 123k/123k [00:00<00:00, 276kB/s]

17/100: C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T\flac_T\T_0000000016.flac
Downloading to C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T/flac_T/T_0000000017.flac...

100%|██████████| 173k/173k [00:00<00:00, 285kB/s]

18/100: C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T\flac_T\T_0000000017.flac
Downloading to C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T/flac_T/T_0000000018.flac...

100%|██████████| 199k/199k [00:00<00:00, 353kB/s]

19/100: C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T\flac_T\T_0000000018.flac
Downloading to C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T/flac_T/T_0000000019.flac...

100%|██████████| 282k/282k [00:00<00:00, 394kB/s]

20/100: C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T\flac_T\T_0000000019.flac
Downloading to C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T/flac_T/T_0000000020.flac...

100%|██████████| 109k/109k [00:00<00:00, 260kB/s]

21/100: C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T\flac_T\T_0000000020.flac
Downloading to C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T/flac_T/T_0000000021.flac...

100%|██████████| 239k/239k [00:00<00:00, 347kB/s]

22/100: C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T\flac_T\T_0000000021.flac
Downloading to C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T/flac_T/T_0000000022.flac...

100%|██████████| 220k/220k [00:00<00:00, 403kB/s]

23/100: C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T\flac_T\T_0000000022.flac
Downloading to C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T/flac_T/T_0000000023.flac...

100%|██████████| 125k/125k [00:00<00:00, 312kB/s]

24/100: C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T\flac_T\T_0000000023.flac
Downloading to C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T/flac_T/T_0000000024.flac...

100%|██████████| 283k/283k [00:00<00:00, 448kB/s]

25/100: C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T\flac_T\T_0000000024.flac
Downloading to C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T/flac_T/T_0000000025.flac...

100%|██████████| 183k/183k [00:00<00:00, 348kB/s]

26/100: C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T\flac_T\T_0000000025.flac
Downloading to C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T/flac_T/T_0000000026.flac...

100%|██████████| 174k/174k [00:00<00:00, 295kB/s]

27/100: C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T\flac_T\T_0000000026.flac
Downloading to C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T/flac_T/T_0000000027.flac...

100%|██████████| 139k/139k [00:00<00:00, 373kB/s]

28/100: C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T\flac_T\T_0000000027.flac
Downloading to C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T/flac_T/T_0000000028.flac...

100%|██████████| 208k/208k [00:00<00:00, 366kB/s]

29/100: C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T\flac_T\T_0000000028.flac
Downloading to C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T/flac_T/T_0000000029.flac...

100%|██████████| 279k/279k [00:00<00:00, 391kB/s]

30/100: C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T\flac_T\T_0000000029.flac
Downloading to C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T/flac_T/T_0000000030.flac...

100%|██████████| 176k/176k [00:00<00:00, 341kB/s]

31/100: C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T\flac_T\T_0000000030.flac
Downloading to C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T/flac_T/T_0000000031.flac...

100%|██████████| 173k/173k [00:00<00:00, 280kB/s]

32/100: C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T\flac_T\T_0000000031.flac
Downloading to C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T/flac_T/T_0000000032.flac...

100%|██████████| 222k/222k [00:00<00:00, 391kB/s]

33/100: C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T\flac_T\T_0000000032.flac
Downloading to C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T/flac_T/T_0000000033.flac...

100%|██████████| 152k/152k [00:01<00:00, 132kB/s]

34/100: C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T\flac_T\T_0000000033.flac
Downloading to C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T/flac_T/T_0000000034.flac...

100%|██████████| 191k/191k [00:00<00:00, 357kB/s]

35/100: C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T\flac_T\T_0000000034.flac
Downloading to C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T/flac_T/T_0000000035.flac...

100%|██████████| 244k/244k [00:00<00:00, 419kB/s]

36/100: C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T\flac_T\T_0000000035.flac
Downloading to C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T/flac_T/T_0000000036.flac...

100%|██████████| 206k/206k [00:00<00:00, 297kB/s]

37/100: C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T\flac_T\T_0000000036.flac
Downloading to C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T/flac_T/T_0000000037.flac...

100%|██████████| 171k/171k [00:00<00:00, 327kB/s]

38/100: C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T\flac_T\T_0000000037.flac
Downloading to C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T/flac_T/T_0000000038.flac...

100%|██████████| 166k/166k [00:00<00:00, 368kB/s]

39/100: C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T\flac_T\T_0000000038.flac
Downloading to C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T/flac_T/T_0000000039.flac...

100%|██████████| 156k/156k [00:00<00:00, 315kB/s]

40/100: C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T\flac_T\T_0000000039.flac
Downloading to C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T/flac_T/T_0000000040.flac...

100%|██████████| 124k/124k [00:00<00:00, 284kB/s]

41/100: C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T\flac_T\T_0000000040.flac
Downloading to C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T/flac_T/T_0000000041.flac...

100%|██████████| 245k/245k [00:00<00:00, 363kB/s]

42/100: C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T\flac_T\T_0000000041.flac
Downloading to C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T/flac_T/T_0000000042.flac...

100%|██████████| 196k/196k [00:00<00:00, 349kB/s]

43/100: C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T\flac_T\T_0000000042.flac
Downloading to C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T/flac_T/T_0000000043.flac...

100%|██████████| 194k/194k [00:00<00:00, 359kB/s]

44/100: C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T\flac_T\T_0000000043.flac
Downloading to C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T/flac_T/T_0000000044.flac...

100%|██████████| 141k/141k [00:00<00:00, 310kB/s]

45/100: C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T\flac_T\T_0000000044.flac
Downloading to C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T/flac_T/T_0000000045.flac...

100%|██████████| 204k/204k [00:00<00:00, 364kB/s]

46/100: C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T\flac_T\T_0000000045.flac
Downloading to C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T/flac_T/T_0000000046.flac...

100%|██████████| 233k/233k [00:00<00:00, 312kB/s]

47/100: C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T\flac_T\T_0000000046.flac
Downloading to C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T/flac_T/T_0000000047.flac...

100%|██████████| 199k/199k [00:00<00:00, 323kB/s]

48/100: C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T\flac_T\T_0000000047.flac
Downloading to C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T/flac_T/T_0000000048.flac...

100%|██████████| 173k/173k [00:00<00:00, 307kB/s]

49/100: C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T\flac_T\T_0000000048.flac
Downloading to C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T/flac_T/T_0000000049.flac...

100%|██████████| 339k/339k [00:00<00:00, 521kB/s]

50/100: C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T\flac_T\T_0000000049.flac
Downloading to C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T/flac_T/T_0000000050.flac...

100%|██████████| 139k/139k [00:00<00:00, 311kB/s]

51/100: C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T\flac_T\T_0000000050.flac
Downloading to C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T/flac_T/T_0000000051.flac...

100%|██████████| 329k/329k [00:01<00:00, 278kB/s]

52/100: C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T\flac_T\T_0000000051.flac
Downloading to C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T/flac_T/T_0000000052.flac...

100%|██████████| 183k/183k [00:00<00:00, 268kB/s]

53/100: C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T\flac_T\T_0000000052.flac
Downloading to C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T/flac_T/T_0000000053.flac...

100%|██████████| 156k/156k [00:00<00:00, 315kB/s]

54/100: C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T\flac_T\T_0000000053.flac
Downloading to C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T/flac_T/T_0000000054.flac...

100%|██████████| 342k/342k [00:00<00:00, 439kB/s]

55/100: C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T\flac_T\T_0000000054.flac
Downloading to C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T/flac_T/T_0000000055.flac...

100%|██████████| 154k/154k [00:00<00:00, 316kB/s]

56/100: C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T\flac_T\T_0000000055.flac
Downloading to C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T/flac_T/T_0000000056.flac...

100%|██████████| 265k/265k [00:00<00:00, 398kB/s]

57/100: C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T\flac_T\T_0000000056.flac
Downloading to C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T/flac_T/T_0000000057.flac...

100%|██████████| 252k/252k [00:00<00:00, 414kB/s]

58/100: C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T\flac_T\T_0000000057.flac
Downloading to C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T/flac_T/T_0000000058.flac...

100%|██████████| 213k/213k [00:00<00:00, 282kB/s]

59/100: C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T\flac_T\T_0000000058.flac
Downloading to C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T/flac_T/T_0000000059.flac...

100%|██████████| 181k/181k [00:00<00:00, 353kB/s]

60/100: C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T\flac_T\T_0000000059.flac
Downloading to C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T/flac_T/T_0000000060.flac...

100%|██████████| 237k/237k [00:00<00:00, 289kB/s]

61/100: C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T\flac_T\T_0000000060.flac
Downloading to C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T/flac_T/T_0000000061.flac...

100%|██████████| 151k/151k [00:00<00:00, 281kB/s]

62/100: C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T\flac_T\T_0000000061.flac
Downloading to C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T/flac_T/T_0000000062.flac...

100%|██████████| 284k/284k [00:01<00:00, 207kB/s]

63/100: C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T\flac_T\T_0000000062.flac
Downloading to C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T/flac_T/T_0000000063.flac...

100%|██████████| 138k/138k [00:00<00:00, 253kB/s]

64/100: C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T\flac_T\T_0000000063.flac
Downloading to C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T/flac_T/T_0000000064.flac...

100%|██████████| 327k/327k [00:00<00:00, 514kB/s]

65/100: C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T\flac_T\T_0000000064.flac
Downloading to C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T/flac_T/T_0000000065.flac...

100%|██████████| 210k/210k [00:00<00:00, 403kB/s]

66/100: C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T\flac_T\T_0000000065.flac
Downloading to C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T/flac_T/T_0000000066.flac...

100%|██████████| 222k/222k [00:00<00:00, 412kB/s]

67/100: C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T\flac_T\T_0000000066.flac
Downloading to C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T/flac_T/T_0000000067.flac...

100%|██████████| 142k/142k [00:00<00:00, 294kB/s]

68/100: C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T\flac_T\T_0000000067.flac
Downloading to C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T/flac_T/T_0000000068.flac...

100%|██████████| 173k/173k [00:00<00:00, 322kB/s]

69/100: C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T\flac_T\T_0000000068.flac
Downloading to C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T/flac_T/T_0000000069.flac...

100%|██████████| 291k/291k [00:00<00:00, 330kB/s]

70/100: C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T\flac_T\T_0000000069.flac
Downloading to C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T/flac_T/T_0000000070.flac...

100%|██████████| 199k/199k [00:00<00:00, 316kB/s]

71/100: C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T\flac_T\T_0000000070.flac
Downloading to C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T/flac_T/T_0000000071.flac...

100%|██████████| 133k/133k [00:00<00:00, 249kB/s]

72/100: C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T\flac_T\T_0000000071.flac
Downloading to C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T/flac_T/T_0000000072.flac...

100%|██████████| 132k/132k [00:00<00:00, 326kB/s]

73/100: C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T\flac_T\T_0000000072.flac
Downloading to C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T/flac_T/T_0000000073.flac...

100%|██████████| 144k/144k [00:00<00:00, 296kB/s]

74/100: C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T\flac_T\T_0000000073.flac
Downloading to C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T/flac_T/T_0000000074.flac...

100%|██████████| 297k/297k [00:00<00:00, 476kB/s]

75/100: C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T\flac_T\T_0000000074.flac
Downloading to C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T/flac_T/T_0000000075.flac...

100%|██████████| 247k/247k [00:00<00:00, 427kB/s]

76/100: C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T\flac_T\T_0000000075.flac
Downloading to C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T/flac_T/T_0000000076.flac...

100%|██████████| 147k/147k [00:00<00:00, 320kB/s]

77/100: C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T\flac_T\T_0000000076.flac
Downloading to C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T/flac_T/T_0000000077.flac...

100%|██████████| 190k/190k [00:00<00:00, 297kB/s]

78/100: C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T\flac_T\T_0000000077.flac
Downloading to C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T/flac_T/T_0000000078.flac...

100%|██████████| 108k/108k [00:00<00:00, 272kB/s]

79/100: C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T\flac_T\T_0000000078.flac
Downloading to C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T/flac_T/T_0000000079.flac...

100%|██████████| 147k/147k [00:00<00:00, 277kB/s]

80/100: C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T\flac_T\T_0000000079.flac
Downloading to C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T/flac_T/T_0000000080.flac...

100%|██████████| 229k/229k [00:00<00:00, 324kB/s]

81/100: C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T\flac_T\T_0000000080.flac
Downloading to C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T/flac_T/T_0000000081.flac...

100%|██████████| 253k/253k [00:00<00:00, 389kB/s]

82/100: C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T\flac_T\T_0000000081.flac
Downloading to C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T/flac_T/T_0000000082.flac...

100%|██████████| 155k/155k [00:00<00:00, 258kB/s]

83/100: C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T\flac_T\T_0000000082.flac
Downloading to C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T/flac_T/T_0000000083.flac...

100%|██████████| 233k/233k [00:00<00:00, 384kB/s]

84/100: C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T\flac_T\T_0000000083.flac
Downloading to C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T/flac_T/T_0000000084.flac...

100%|██████████| 220k/220k [00:00<00:00, 380kB/s]

85/100: C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T\flac_T\T_0000000084.flac
Downloading to C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T/flac_T/T_0000000085.flac...

100%|██████████| 323k/323k [00:00<00:00, 432kB/s]

86/100: C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T\flac_T\T_0000000085.flac
Downloading to C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T/flac_T/T_0000000086.flac...

100%|██████████| 191k/191k [00:00<00:00, 223kB/s]

87/100: C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T\flac_T\T_0000000086.flac
Downloading to C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T/flac_T/T_0000000087.flac...

100%|██████████| 147k/147k [00:00<00:00, 199kB/s]

88/100: C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T\flac_T\T_0000000087.flac
Downloading to C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T/flac_T/T_0000000088.flac...

100%|██████████| 148k/148k [00:00<00:00, 273kB/s]

89/100: C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T\flac_T\T_0000000088.flac
Downloading to C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T/flac_T/T_0000000089.flac...

100%|██████████| 281k/281k [00:00<00:00, 446kB/s]

90/100: C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T\flac_T\T_0000000089.flac
Downloading to C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T/flac_T/T_0000000090.flac...

100%|██████████| 239k/239k [00:00<00:00, 446kB/s]

91/100: C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T\flac_T\T_0000000090.flac
Downloading to C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T/flac_T/T_0000000091.flac...

100%|██████████| 197k/197k [00:00<00:00, 300kB/s]

92/100: C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T\flac_T\T_0000000091.flac
Downloading to C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T/flac_T/T_0000000092.flac...

100%|██████████| 289k/289k [00:00<00:00, 459kB/s]

93/100: C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T\flac_T\T_0000000092.flac
Downloading to C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T/flac_T/T_0000000093.flac...

100%|██████████| 229k/229k [00:01<00:00, 203kB/s]

94/100: C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T\flac_T\T_0000000093.flac
Downloading to C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T/flac_T/T_0000000094.flac...

100%|██████████| 170k/170k [00:00<00:00, 255kB/s]

95/100: C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T\flac_T\T_0000000094.flac
Downloading to C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T/flac_T/T_0000000095.flac...

100%|██████████| 132k/132k [00:00<00:00, 303kB/s]

96/100: C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T\flac_T\T_0000000095.flac
Downloading to C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T/flac_T/T_0000000096.flac...

100%|██████████| 269k/269k [00:00<00:00, 302kB/s]

97/100: C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T\flac_T\T_0000000096.flac
Downloading to C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T/flac_T/T_0000000097.flac...

100%|██████████| 208k/208k [00:00<00:00, 385kB/s]

98/100: C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T\flac_T\T_0000000097.flac
Downloading to C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T/flac_T/T_0000000098.flac...

100%|██████████| 213k/213k [00:01<00:00, 138kB/s]

99/100: C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T\flac_T\T_0000000098.flac
Downloading to C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T/flac_T/T_0000000099.flac...

100%|██████████| 256k/256k [00:01<00:00, 222kB/s]

100/100: C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T\flac_T\T_0000000099.flac
Arquivos disponiveis: 100
Pasta local: C:\Users\prisc\.cache\kagglehub\datasets\ulianazb\asvspoof-2024\versions\2\flac_T\flac_T

In [19]:
from pathlib import Path
import pandas as pd
import soundfile as sf
from tqdm.auto import tqdm
from pyAudioAnalysis import ShortTermFeatures

if not arquivos:
    raise ValueError("Execute primeiro a celula que baixa os 100 arquivos")

raiz = Path(arquivos[0]).parent

registros = []
erros = []

for arquivo in tqdm(arquivos):
    try:
        sinal, fs = sf.read(arquivo, always_2d=True)
        sinal = sinal.mean(axis=1)
        janela = int(0.050 * fs)
        passo = int(0.025 * fs)

        if len(sinal) < janela:
            raise ValueError("Audio menor que a janela de 50 ms")

        features, nomes = ShortTermFeatures.feature_extraction(
            sinal, fs, janela, passo, deltas=False
        )

        registro = {
            "arquivo": str(arquivo.relative_to(raiz)),
            "audio_id": arquivo.stem,
            "duracao_s": len(sinal) / fs,
            "sample_rate": fs,
        }
        for nome, media, desvio in zip(
            nomes, features.mean(axis=1), features.std(axis=1)
        ):
            registro[f"{nome}_mean"] = media
            registro[f"{nome}_std"] = desvio

        registros.append(registro)
    except Exception as erro:
        erros.append({"arquivo": str(arquivo), "erro": str(erro)})

df = pd.DataFrame(registros)
display(df.head())
display(pd.DataFrame(erros))
df.to_csv("audio_features.csv", index=False)
print(f"Tabela gerada: {df.shape[0]} audios, {df.shape[1]} colunas; erros: {len(erros)}")

  0%|          | 0/100 [00:00<?, ?it/s]

100%|██████████| 100/100 [01:46<00:00,  1.07s/it]

,arquivo,audio_id,duracao_s,sample_rate,zcr_mean,zcr_std,energy_mean,energy_std,energy_entropy_mean,energy_entropy_std,...,chroma_9_mean,chroma_9_std,chroma_10_mean,chroma_10_std,chroma_11_mean,chroma_11_std,chroma_12_mean,chroma_12_std,chroma_std_mean,chroma_std_std
0,T_0000000000.flac,T_0000000000,8.896,16000,0.136392,0.166143,0.035569,0.041674,2.753027,0.626027,...,0.004525,0.006642,0.031360,0.037951,0.054832,0.051243,0.006189,0.012895,0.027983,0.017413
1,T_0000000001.flac,T_0000000001,7.344,16000,0.127218,0.110200,0.020658,0.025027,2.934822,0.401091,...,0.012497,0.017206,0.016447,0.024874,0.014035,0.014297,0.011062,0.018033,0.024179,0.014093
2,T_0000000002.flac,T_0000000002,10.832,16000,0.160093,0.169348,0.004572,0.005684,2.744521,0.557182,...,0.005246,0.007243,0.012143,0.012989,0.016503,0.016846,0.004793,0.008144,0.022397,0.013696
3,T_0000000003.flac,T_0000000003,13.024,16000,0.148126,0.167332,0.012719,0.015592,2.789464,0.490564,...,0.005592,0.009822,0.013402,0.016289,0.045857,0.037307,0.005566,0.008019,0.024097,0.014761
4,T_0000000004.flac,T_0000000004,15.456,16000,0.186223,0.160997,0.010344,0.011095,2.811432,0.468673,...,0.007372,0.011351,0.011294,0.015526,0.014703,0.018460,0.007003,0.012710,0.017845,0.013832

Empty DataFrame
Columns: []
Index: []

Tabela gerada: 100 audios, 72 colunas; erros: 0

## EDA

In [18]:
df.info()
df.describe()
df.head()

NameError: name 'df' is not defined